[tasks.ci-bump-version]
workspace = false
command = "./ci/setversion.sh"
args = ["${@}"]

[tasks.ci-build]
workspace = false
dependencies = [
  "build-release",
  "move-artifacts",
]

[tasks.move-artifacts]
script = '''
#!@duckscript

output_dir = set dist
suffix = set ""

if is_windows
    suffix = set ".exe" 
end

target_binary_name = set efiboot
target_binary = set "target/${CARGO_BUILD_TARGET}/release/${target_binary_name}${suffix}"

mkdir ${output_dir}
cp ${target_binary} ${output_dir}/${target_binary_name}_${CARGO_BUILD_TARGET}${suffix}
'''

[tasks.ci-test]
workspace = false
command = "cargo"
args = ["test", "--release"]
