[package]
name = "efivar"
version = "0.2.2"
authors = ["Vincent Tavernier <v.tavernier@pm.me>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/vtavernier/efiboot-rs"
homepage = "https://github.com/vtavernier/efiboot-rs"
documentation = "https://docs.rs/efivar"
keywords = ["efi"]
categories = []
description = """
Rust crate for manipulating EFI variables using the OS interface.
"""
edition = "2018"

[dependencies]
byteorder = "1.3.2"
bitflags = "1.2.1"
failure = "0.1.6"

base64 = { version = "0.11.0", optional = true }
serde = { version = "1.0.104", optional = true }
serde_derive = { version = "1.0.104", optional = true }
toml = { version = "0.5.5", optional = true }
uuid = { version = "1.2.2", features = ["serde"] }
lazy_static = "1.4.0"

[features]
store = ["base64", "serde", "serde_derive", "toml"]

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3.8"
features = ["winbase", "winnt", "processthreadsapi", "securitybaseapi", "handleapi"]

[dev-dependencies]
version-sync = "0.8.1"
