[package]
name = "efiboot"
version = "0.2.2"
authors = ["Vincent Tavernier <vince.tavernier@gmail.com>"]
description = "EFI boot manager variable editor written in Rust"
edition = "2018"

[dependencies]
efivar = { version = "0.2.2", path = "../efivar", features = ["store"] }
itertools = "0.8.2"
paw = "1.0.0"
structopt = { version = "0.3.7", features = ["paw"] }
