[package]
name = "efiboot"
version = "0.2.2"
authors = ["Vincent Tavernier <v.tavernier@pm.me>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/vtavernier/efiboot-rs"
homepage = "https://github.com/vtavernier/efiboot-rs/tree/master/efiboot"
documentation = "https://docs.rs/efiboot"
keywords = ["efi"]
categories = []
description = "EFI boot manager variable editor written in Rust"
edition = "2018"

[dependencies]
efivar = { version = "0.2.2", path = "../efivar", features = ["store"] }
itertools = "0.8.2"
paw = "1.0.0"
structopt = { version = "0.3.7", features = ["paw"] }

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }_{ target }{ archive-suffix }"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "bin"
