name: build

on:
  pull_request:
    branches-ignore:
      - renovate/*
  push:
    branches:
      - master
      - alpha
      - beta
      - renovate/*
    tags-ignore:
      - "**"

concurrency: ci-${{ github.ref }}

jobs:
  check:
    uses: iTrooz/vtavernier-github-workflows/.github/workflows/check-rust.yml@v1

  build:
    uses: iTrooz/vtavernier-github-workflows/.github/workflows/build-rust-bin.yml@v1

    needs:
      - check

    strategy:
      fail-fast: false

      matrix:
        include:
          - runs-on: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - runs-on: windows-latest
            target: x86_64-pc-windows-msvc

    with:
      runs-on: ${{ matrix.runs-on }}
      rust-target: ${{ matrix.target }}
      artifact-name: artifact
      upload-coverage-to: codecov

    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}

