name: pullrequest

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  pullrequest:
    uses: iTrooz/vtavernier-github-workflows/.github/workflows/pullrequest-semantic.yml@v1
